# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Road2QGIS
                                 A QGIS plugin
 Plugin faisant appel au calcul d'itinéraires du Géoportail pour intégration dans QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-07
        copyright            : (C) 2022 by azarz
        email                : amaury.zarzelli@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Road2QGIS class from file Road2QGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from road2qgis.main import Road2QGIS
    return Road2QGIS(iface)
